#!/bin/zsh

set -euo pipefail

script_dir=${0:A:h}
repo_root=${script_dir:h}
manifest_file="$repo_root/manifest.json"
sync_tmp=$(mktemp -d /tmp/mysurge-sync.XXXXXX)
lock_tmp="$sync_tmp/sources.lock"
fallback_hosts=${MYSURGE_CI_FALLBACK_HOSTS:-}
fallback_hosts=${fallback_hosts// /}

function is_fallback_url() {
  local url_without_scheme=${1#*://}
  local url_host=${url_without_scheme%%/*}
  [[ ",${fallback_hosts:l}," == *",${url_host:l},"* ]]
}

print '# Generated by scripts/sync.sh' > "$lock_tmp"
print '# id<TAB>sha256<TAB>upstream_url' >> "$lock_tmp"

while IFS=$'\t' read -r module_id upstream_url local_path; do
  upstream_file="$sync_tmp/$module_id.upstream"
  normalized_file="$sync_tmp/$module_id.sgmodule"
  target_file="$repo_root/$local_path"

  if ! http_meta=$(curl --globoff -L --fail --silent --show-error \
    --user-agent 'Surge iOS/6.0' \
    --max-time 30 \
    --output "$upstream_file" \
    --write-out '%{http_code} %{content_type}' \
    "$upstream_url"); then
    if ! is_fallback_url "$upstream_url"; then
      exit 1
    fi

    locked_sha=$(awk -F $'\t' -v id="$module_id" '$1 == id {print $2}' "$repo_root/sources.lock")
    locked_url=$(awk -F $'\t' -v id="$module_id" '$1 == id {print $3}' "$repo_root/sources.lock")

    if [[ ! -s "$target_file" || ! "$locked_sha" =~ '^[0-9a-f]{64}$' || "$locked_url" != "$upstream_url" ]]; then
      print -u2 "Cannot preserve locked fallback snapshot: $module_id"
      exit 1
    fi

    printf '%s\t%s\t%s\n' "$module_id" "$locked_sha" "$upstream_url" >> "$lock_tmp"
    printf '%-20s %-30s %8s bytes  %s\n' \
      "$module_id" 'fallback: locked snapshot' "$(wc -c < "$target_file" | tr -d ' ')" "$locked_sha"

    if [[ "${GITHUB_ACTIONS:-}" == true ]]; then
      print "::warning title=Upstream unavailable::$module_id kept its locked snapshot ($upstream_url)"
    fi
    continue
  fi

  awk '
    BEGIN { category_added = 0 }
    {
      gsub(/\r/, "")
      sub(/^﻿/, "")
      if ($0 ~ /^#!category[[:space:]]*=/) {
        next
      }
      print
      if (!category_added && $0 ~ /^#!name[[:space:]]*=/) {
        print "#!category=vpromise"
        category_added = 1
      }
    }
    END {
      if (!category_added) {
        print "#!category=vpromise"
      }
    }
  ' "$upstream_file" > "$normalized_file"
  perl -0pi -e 's/\n+\z/\n/' "$normalized_file"

  mkdir -p "${target_file:h}"
  cp "$normalized_file" "$target_file"

  upstream_sha=$(shasum -a 256 "$upstream_file" | awk '{print $1}')
  printf '%s\t%s\t%s\n' "$module_id" "$upstream_sha" "$upstream_url" >> "$lock_tmp"
  printf '%-20s %-30s %8s bytes  %s\n' \
    "$module_id" "$http_meta" "$(wc -c < "$target_file" | tr -d ' ')" "$upstream_sha"
done < <(jq -r '.modules[] | select(.upstreamUrl != null) | [.id, .upstreamUrl, .localPath] | @tsv' "$manifest_file")

cp "$lock_tmp" "$repo_root/sources.lock"
printf '\nSynced modules with category=vpromise\n'
printf 'Source lock: %s\n' "$repo_root/sources.lock"
printf 'Temporary files: %s\n' "$sync_tmp"
