#!/bin/zsh

set -euo pipefail

script_dir=${0:A:h}
repo_root=${script_dir:h}
manifest_file="$repo_root/manifest.json"
sync_tmp=$(mktemp -d /tmp/mysurge-sync.XXXXXX)
lock_tmp="$sync_tmp/sources.lock"

print '# Generated by scripts/sync.sh' > "$lock_tmp"
print '# id<TAB>sha256<TAB>upstream_url' >> "$lock_tmp"

while IFS=$'\t' read -r module_id upstream_url local_path; do
  upstream_file="$sync_tmp/$module_id.upstream"
  normalized_file="$sync_tmp/$module_id.sgmodule"
  target_file="$repo_root/$local_path"

  http_meta=$(curl --globoff -L --fail --silent --show-error \
    --user-agent 'Surge iOS/6.0' \
    --max-time 30 \
    --output "$upstream_file" \
    --write-out '%{http_code} %{content_type}' \
    "$upstream_url")

  awk '
    BEGIN { category_added = 0 }
    {
      gsub(/\r/, "")
      sub(/^﻿/, "")
      if ($0 ~ /^#!category[[:space:]]*=/) {
        next
      }
      print
      if (!category_added && $0 ~ /^#!name[[:space:]]*=/) {
        print "#!category=vpromise"
        category_added = 1
      }
    }
    END {
      if (!category_added) {
        print "#!category=vpromise"
      }
    }
  ' "$upstream_file" > "$normalized_file"
  perl -0pi -e 's/\n+\z/\n/' "$normalized_file"

  mkdir -p "${target_file:h}"
  cp "$normalized_file" "$target_file"

  upstream_sha=$(shasum -a 256 "$upstream_file" | awk '{print $1}')
  printf '%s\t%s\t%s\n' "$module_id" "$upstream_sha" "$upstream_url" >> "$lock_tmp"
  printf '%-20s %-30s %8s bytes  %s\n' \
    "$module_id" "$http_meta" "$(wc -c < "$target_file" | tr -d ' ')" "$upstream_sha"
done < <(jq -r '.modules[] | select(.upstreamUrl != null) | [.id, .upstreamUrl, .localPath] | @tsv' "$manifest_file")

cp "$lock_tmp" "$repo_root/sources.lock"
printf '\nSynced modules with category=vpromise\n'
printf 'Source lock: %s\n' "$repo_root/sources.lock"
printf 'Temporary files: %s\n' "$sync_tmp"
